- type: job
  id: TownSheriff
  setPreference: true
  name: job-name-townsheriff
  description: job-description-townsheriff
  playTimeTracker: TownSheriff
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: Townsfolk
      min: 28800 # 8 hours
    - !type:CharacterPlaytimeRequirement # Corvax-Add
      tracker: TownDeputy
      min: 14400 # 4 hours
  startingGear: TownSheriffGear
  icon: "JobIconTownSheriff" # Corvax-Change
  supervisors: job-supervisors-townsfolk
  access:
  - TownieLaw
  - TownieMechanic
  - TownieDoctor
  - WastelandReporter
  - TownsPerson # Corvax-Change
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Townsfolk

#- type: startingGear
#  id: TownSheriffGear
#  equipment:
#    jumpsuit: N14ClothingUniformJumpsuitCowboyGrey
#    back: N14ClothingBackpackSheriffFilled
#    shoes: N14ClothingBootsCowboy
#    head: N14ClothingHeadHatSheriff
#    eyes: N14ClothingEyesSunGlasses
#    id: N14IDBadgeTownSheriff
#    outerClothing: N14ClothingOuterSheriffVest
#    belt: ClothingBeltRevolverWildWhisper
#    pocket1: RadioHandheld
#    pocket2: Handcuffs
#  satchel: N14ClothingBackpackSatchelSheriffFilled
#  duffelbag: N14ClothingBackpackDuffelSheriffFilled

- type: playTimeTracker
  id: TownSheriff
