- type: job
  id: TownMayor
  setPreference: true
  name: job-name-townmayor
  description: job-description-townmayor
  playTimeTracker: TownMayor
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: Townsfolk
      min: 36000 # 10 hours
  startingGear: TownMayorGear
  icon: "JobIconTownMayor" # Corvax-Change
  supervisors: job-supervisors-townsfolk
  accessGroups:
  - Townie
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Townsfolk

- type: startingGear
  id: TownMayorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCheckered
    back: N14ClothingBackpackExplorer # Corvax-Change
    shoes: N14ClothingShoesBrown
    id: N14IDBadgeTownMayor
    pocket1: RadioHandheld
    belt: N14WalletLottaCash
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelMayorFilled
  duffelbag: N14ClothingBackpackDuffelMayorFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: TownMayor
