- type: job
  id: BoSWestPaladin
  setPreference: true
  name: job-name-bos-west-paladin
  description: job-description-bos-west-paladin
  playTimeTracker: BoSWestPaladin
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWest
      min: 108000 # 30 hours
  startingGear: BoSWestPaladinGear
  alwaysUseSpawner: true
  icon: "JobIconBosMPaladin"
  supervisors: job-supervisors-bos-west
  canBeAntag: false
  access:
  - BoSWest
  - WestPaladin
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWest

- type: startingGear
  id: BoSWestPaladinGear
  equipment:
    jumpsuit: N14ClothingUniformBosRecon
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    head:  N14ClothingHeadHatBrotherhoodFieldCap
    outerClothing: N14ClothingOuterMidwestArmorMK2
    pocket1: NCRBoSMidwestPaladinkits
    hands: N14ClothingHandsGlovesCombat
    id: N14IDBrotherhoodHolotagPaladin
    ears: N14ClothingHeadsetBOSMidwest
    belt: ClothingBeltMilitary
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWestPaladin
