- type: job
  id: CaravanTrader
  setPreference: true
  name: job-name-caravan-trader
  description: job-description-caravan-trader
  playTimeTracker: CaravanTrader
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterOverallTimeRequirement
      min: 7200
  startingGear: CaravanTraderGear
  icon: "JobIconCaravanTrader" # Corvax-Change
  supervisors: job-supervisors-caravan
  alwaysUseSpawner: true
  access:
  - CaravanCompanyTrader
  - CaravanCompanyGuard
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaravanCompany

- type: startingGear
  id: CaravanTraderGear
  equipment:
    head: N14ClothingHeadHatCaravanUniform
    jumpsuit: N14ClothingUniformJumpsuitCaravanShirt
    back: N14ClothingBackpackHiking # Corvax-Change
    shoes: N14ClothingShoesBrown
    id: N14IDPassportCaravanTrader
    outerClothing: ClothingOuterVest
    suitstorage: N14WeaponSMG45 # Corvax-Change
  innerClothingSkirt: N14ClothingUniformJumpsuitTrader #placeholder
  satchel: N14ClothingBackpackSatchelCaravanFilled
  duffelbag: N14ClothingBackpackDuffelCaravanFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander
    - Magazine45SubMachineGun
    - Magazine45SubMachineGun

- type: playTimeTracker
  id: CaravanTrader
