- type: job
  id: TribalHealer
  setPreference: true
  name: job-name-tribal-healer
  description: job-description-tribal-healer
  playTimeTracker: TribalHealer
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: Tribe
      min: 7200 # 2 hours
  startingGear: TribalHealerGear
  alwaysUseSpawner: true
  icon: "JobIconTribalMedic" # Corvax-Change
  supervisors: job-supervisors-tribal
  access:
  - TribeMember
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Tribal
      - type: CPRTraining
  - !type:AddTraitSpecial
    traits: [ LanguageTribal ]

- type: startingGear
  id: TribalHealerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    outerClothing: N14ClothingOuterTribalArmor
    shoes: N14ClothingShoesTribal
    gloves: N14ClothingHandsGlovesTribal
    back: N14ClothingBackpackTrekker # Corvax-Change
    pocket1: N14TribalKnife
    id: N14IDTribeSawbonePendant
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: N14ClothingBackpackSatchelTribalHealerFilled
  storage: # Corvax-Change
    back:
    - Torch
    - Torch
    - Torch
    - N14Bandage
    - N14Bandage
    - Ointment
    - N14HealingPowder
    - N14HealingPowder

- type: playTimeTracker
  id: TribalHealer
