- type: department
  id: CaesarLegion
  description: department-CaesarLegion-description
  color: "#950202"
  roles:
  - CaesarLegionCenturion
  - CaesarLegionVenator
  - CaesarLegionDean
  - CaesarLegionLegionnaireVeteran
  - CaesarLegionLegionnaireWarrior
  - CaesarLegionLegionnaireRecruit

- type: department
  id: Raider
  description: department-Raider-description
  color: "#093f09"
  roles:
  - Raider

- type: department
  id: BrotherhoodWest
  description: department-BrotherhoodWest-description
  color: "#0c0fb1"
  roles:
  - BoSWestElderCommander
  - BoSWestGunsmith
  - BoSWestPaladin
  - BoSWestScribe
  - BoSWestKnight
