- type: job
  id: WastelandFarmer
  setPreference: true
  name: job-name-farmer
  description: job-description-farmer
  playTimeTracker: Farmer
  startingGear: FarmerGear
  icon: "JobIconWastelandFarmer" # Corvax-Change
  supervisors: job-supervisors-wastelander
  access:
  - WastelandFarmer
  - TownsPerson # Corvax-Change

- type: startingGear
  id: FarmerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBrahminFarmer
    back: N14ClothingBackpackExplorer # Corvax-Change
    shoes: N14ClothingBootsLeather
    outerClothing: ClothingOuterApronBotanist
    belt: N14ClothingBeltPlantFilled
    id: N14IDPassportWasteFarmer # Corvax-Change
  innerClothingSkirt: N14ClothingUniformJumpsuitBrahminFarmer #placeholder
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: Farmer
