- type: job
  id: CaesarLegionCenturion
  setPreference: true
  name: job-name-caesar-legion-centurion
  description: job-description-caesar-legion-centurion
  playTimeTracker: CaesarLegionCenturion
  requirements:
  - !type:CharacterDepartmentTimeRequirement
      department: CaesarLegion
      min: 216000 # 60 hours
  - !type:CharacterPlaytimeRequirement
      tracker: CaesarLegionDean
      min: 43200 # 12 hours
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterSexRequirement
    sex: Male
  - !type:CharacterGenderRequirement
    gender: Male
  startingGear: CaesarLegionCenturionGear
  alwaysUseSpawner: true
  icon: "JobIconLegioner"
  supervisors: job-name-caesar-legion
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
      - type: ReplacementAccent
        accent: latin
  - !type:AddTraitSpecial
    traits: [ LanguageLatin ]

- type: startingGear
  id: CaesarLegionCenturionGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    neck: ClothingNeckBlackScarf
    eyes: N14ClothingEyesGlassesWelding
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCenturion
    head: N14ClothingHeadHatCenturionHelmet
    gloves: N14ClothingHandsGlovesCenturion
    outerClothing: N14ClothingOuterHeavyCenturionArmor
    belt: N14Gladius
    pocket1: LegionCenturionloadoutkits
    pocket2: N14WeaponPistol10mmPipe
    id: N14IDLegionaryMedalGold
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: CaesarLegionCenturion
