# MARK: Ranger
- type: loadout
  id: LoadoutNCRRangerVest
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerVest

- type: loadout
  id: LoadoutNCRRangerArmorB
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerArmorB

- type: loadout
  id: LoadoutNCRRangerDuster
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerDuster

- type: loadout
  id: LoadoutNCRhelmet
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmet

- type: loadout
  id: LoadoutNCRmaskBroken
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerBroken

- type: loadout
  id: LoadoutNCRmaskCombat
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasCombat

#Corvax-Add Start
- type: loadout
  id: LoadoutNCRRangerCoat
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerCoat

- type: loadout
  id: LoadoutNCRClothingMaskGasRangerDesert1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerDesert

- type: loadout
  id: LoadoutNCRClothingMaskGasRangerOld1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerOld

- type: loadout
  id: LoadoutNCRClothingMaskGasRangerPrice1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerPrice

- type: loadout
  id: LoadoutNCRClothingMaskGasRangerElite1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerElite

- type: loadout
  id: LoadoutNCRClothingMaskGasRangerModif1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerModif

- type: loadout
  id: LoadoutNCRClothingMaskGasRangerWeathered
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerWeathered

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmetDesert1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetDesert

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmetOld
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetOld

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmetPrice1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetPrice

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmetFox1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetFox

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmetModif1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetModif

- type: loadout
  id: LoadoutNCRN14ClothingNeckCloakRanger
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingNeckCloakRanger

- type: loadout
  id: LoadoutNCRClothingMaskGasRanger1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRanger

- type: loadout
  id: LoadoutNCRClothingMaskGasRiot1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRiot
# Corvax-Add End

- type: loadout
  id: LoadoutNCRhatB
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerB

- type: loadout
  id: LoadoutNCRhatBeret
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatNCRBeretRecon

- type: loadout
  id: LoadoutNCRmaskDesert
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingMaskDesertMask

- type: loadout
  id: LoadoutNCRuniformV1
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV1

- type: loadout
  id: LoadoutNCRuniformV2
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV2

- type: loadout
  id: LoadoutNCRuniformV3
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV3

- type: loadout
  id: LoadoutNCRuniformPants
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPants

- type: loadout
  id: LoadoutNCRuniformDesertPantsFull
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPantsFull

- type: loadout
  id: LoadoutNCRgloves
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHandsGlovesNCR

# misc
- type: loadout
  id: LoadoutNCRRangerMedkit
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MedkitCombatFilled

# Corvax-Add Start
- type: loadout
  id: LoadoutNCRN14ClothingUniformRangerVeteranRed
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteranRed

- type: loadout
  id: LoadoutNCRN14ClothingUniformRangerVeteran
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteran

- type: loadout
  id: LoadoutNCRN14ClothingUniformRangerVeteranBlack
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteranBlack

- type: loadout
  id: LoadoutNCRN14ClothingUniformRangerBlue
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerBlue

- type: loadout
  id: LoadoutNCRN14ClothingUniformRangerModif
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerModif

- type: loadout
  id: LoadoutNCRClothingNeckOldMantle
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - ClothingNeckOldMantle
# Corvax-Add End

- type: loadout
  id: LoadoutNCRuniformHelmetDesert
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetDesert

- type: loadout
  id: LoadoutNCRuniformMaskDesert
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRangerDesert

- type: loadout
  id: LoadoutNCRuniformCombatDesert 
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerCombatDesert

- type: loadout
  id: LoadoutNCRRangerEliteOld
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingOuterRangerEliteOld

- type: loadout
  id: LoadoutNCRRangerHelmetEliteOld
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingHeadHatRangerHelmetEliteOld

# Corvax-Add Start
- type: loadout
  id: LoadoutNCRClothingMaskGasRangerElite2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - ClothingMaskGasRangerElite

- type: loadout
  id: LoadoutNCRClothingMaskGasRangerPrice2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRangerPrice

- type: loadout
  id: LoadoutNCRClothingMaskGasRangerModif2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRangerModif

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmetFox2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetFox

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmetPrice2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetPrice

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmetModif2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetModif

- type: loadout
  id: LoadoutNCRN14ClothingHeadHatRangerHelmet2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmet

- type: loadout
  id: LoadoutNCRN14ClothingOuterRangerWeathered
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerWeathered

- type: loadout
  id: LoadoutNCRN14ClothingOuterRangerFox
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerFox

- type: loadout
  id: LoadoutNCRN14ClothingOuterRangerPrice
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerPrice

- type: loadout
  id: LoadoutNCRNeckCloakRangerPoncho
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingNeckCloakRangerPoncho

- type: loadout
  id: LoadoutNCRClothingMaskGasRanger2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRanger

- type: loadout
  id: LoadoutNCRClothingMaskGasRiot2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRiot
# Corvax-Add End
